package com.erasm.core.service.impl;

import com.erasm.core.dto.response.AllocationResponse;
import com.erasm.core.dto.response.SkillReportResponse;
import com.erasm.core.dto.response.UtilizationReportResponse;
import com.erasm.core.entity.AuditLog;
import com.erasm.core.exception.ReportGenerationException;
import com.erasm.core.repository.AuditLogRepository;
import com.erasm.core.service.ReportExportService;
import com.erasm.core.service.ReportService;
import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.apache.poi.xwpf.usermodel.XWPFTable;
import org.apache.poi.xwpf.usermodel.XWPFTableRow;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Service
public class ReportExportServiceImpl implements ReportExportService {

    private static final Logger logger = LoggerFactory.getLogger(ReportExportServiceImpl.class);

    private final ReportService reportService;
    private final AuditLogRepository auditLogRepository;

    public ReportExportServiceImpl(ReportService reportService, AuditLogRepository auditLogRepository) {
        this.reportService = reportService;
        this.auditLogRepository = auditLogRepository;
    }

    private static final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    // ==========================================
    // PDF Helper Methods
    // ==========================================
    private Document createPdfDocument(ByteArrayOutputStream out, String title, int tableColumns, List<String> headers, PdfTableDataFiller filler) {
        Document document = new Document(PageSize.A4);
        try {
            PdfWriter.getInstance(document, out);
            document.open();

            // Header/Logo section
            Font companyFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, java.awt.Color.DARK_GRAY);
            Paragraph companyPara = new Paragraph("ERASM ENTERPRISE SYSTEM", companyFont);
            companyPara.setAlignment(Element.ALIGN_CENTER);
            document.add(companyPara);

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, java.awt.Color.BLUE);
            Paragraph titlePara = new Paragraph(title, titleFont);
            titlePara.setAlignment(Element.ALIGN_CENTER);
            titlePara.setSpacingAfter(20);
            document.add(titlePara);

            // Metadata section
            Font metaFont = FontFactory.getFont(FontFactory.HELVETICA, 10, java.awt.Color.BLACK);
            Paragraph metaPara = new Paragraph("Generated Date: " + LocalDateTime.now().format(formatter) + " | Generated By: ERASM Admin", metaFont);
            metaPara.setSpacingAfter(15);
            document.add(metaPara);

            // Table Creation
            PdfPTable table = new PdfPTable(tableColumns);
            table.setWidthPercentage(100f);

            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, java.awt.Color.WHITE);
            for (String header : headers) {
                PdfPCell cell = new PdfPCell(new Paragraph(header, headerFont));
                cell.setBackgroundColor(java.awt.Color.BLUE);
                cell.setPadding(6);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                table.addCell(cell);
            }

            filler.fillTable(table);
            document.add(table);

            // Footer
            Paragraph footer = new Paragraph("\nPage 1 of 1 — Confidential — Generated by ERASM Reports Engine", FontFactory.getFont(FontFactory.HELVETICA, 8, java.awt.Color.GRAY));
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();
        } catch (Exception e) {
            logger.error("Error generating PDF: " + e.getMessage(), e);
            throw new ReportGenerationException("Error generating PDF report: " + e.getMessage());
        }
        return document;
    }

    interface PdfTableDataFiller {
        void fillTable(PdfPTable table);
    }

    // ==========================================
    // PDF Reports Implementation
    // ==========================================
    @Override
    @Transactional(readOnly = true)
    public byte[] exportProjectsPdf() {
        logger.info("Exporting projects allocation report to PDF");
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        List<AllocationResponse> allocations = reportService.getProjectAllocationReport();
        List<String> headers = List.of("ID", "Project Name", "Employee Name", "Allocation %", "Start Date", "End Date", "Status");

        createPdfDocument(out, "Project Allocations Report", 7, headers, table -> {
            Font cellFont = FontFactory.getFont(FontFactory.HELVETICA, 9);
            for (AllocationResponse alloc : allocations) {
                table.addCell(new PdfPCell(new Paragraph(alloc.getAllocationId() != null ? alloc.getAllocationId().toString() : "", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(alloc.getProjectName() != null ? alloc.getProjectName() : "", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(alloc.getEmployeeName() != null ? alloc.getEmployeeName() : "", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(alloc.getAllocationPercentage() != null ? alloc.getAllocationPercentage().toString() + "%" : "0%", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(alloc.getStartDate() != null ? alloc.getStartDate().toString() : "", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(alloc.getEndDate() != null ? alloc.getEndDate().toString() : "-", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(alloc.getStatus() != null ? alloc.getStatus().toString() : "", cellFont)));
            }
        });
        return out.toByteArray();
    }

    @Override
    @Transactional(readOnly = true)
    public byte[] exportUtilizationPdf() {
        logger.info("Exporting utilization report to PDF");
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        List<UtilizationReportResponse> utils = reportService.getUtilizationReport();
        List<String> headers = List.of("Employee ID", "Employee Name", "Department", "Allocated %", "Billable %", "Bench %");

        createPdfDocument(out, "Resource Utilization Report", 6, headers, table -> {
            Font cellFont = FontFactory.getFont(FontFactory.HELVETICA, 9);
            for (UtilizationReportResponse ut : utils) {
                table.addCell(new PdfPCell(new Paragraph(ut.getEmployeeId() != null ? ut.getEmployeeId().toString() : "", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(ut.getEmployeeName() != null ? ut.getEmployeeName() : "", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(ut.getDepartment() != null ? ut.getDepartment() : "", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(ut.getTotalAllocatedPercentage() != null ? ut.getTotalAllocatedPercentage().toString() + "%" : "0%", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(ut.getBillablePercentage() != null ? ut.getBillablePercentage().toString() + "%" : "0%", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(ut.getBenchPercentage() != null ? ut.getBenchPercentage().toString() + "%" : "100%", cellFont)));
            }
        });
        return out.toByteArray();
    }

    @Override
    @Transactional(readOnly = true)
    public byte[] exportSkillsPdf() {
        logger.info("Exporting skills report to PDF");
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        List<SkillReportResponse> skills = reportService.getSkillReport();
        List<String> headers = List.of("Skill ID", "Skill Name", "Category", "Count of Employees");

        createPdfDocument(out, "Skills Distribution Report", 4, headers, table -> {
            Font cellFont = FontFactory.getFont(FontFactory.HELVETICA, 9);
            for (SkillReportResponse sk : skills) {
                table.addCell(new PdfPCell(new Paragraph(sk.getSkillId() != null ? sk.getSkillId().toString() : "", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(sk.getSkillName() != null ? sk.getSkillName() : "", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(sk.getCategory() != null ? sk.getCategory() : "", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(String.valueOf(sk.getCount()), cellFont)));
            }
        });
        return out.toByteArray();
    }

    @Override
    @Transactional(readOnly = true)
    public byte[] exportAuditPdf() {
        logger.info("Exporting audit logs to PDF");
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        List<AuditLog> logs = auditLogRepository.findAllByOrderByTimestampDesc();
        List<String> headers = List.of("Log ID", "Action", "Entity", "Entity ID", "Performed By", "Timestamp", "Details");

        createPdfDocument(out, "Audit Trail Report", 7, headers, table -> {
            Font cellFont = FontFactory.getFont(FontFactory.HELVETICA, 8);
            for (AuditLog log : logs) {
                table.addCell(new PdfPCell(new Paragraph(log.getLogId() != null ? log.getLogId().toString() : "", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(log.getAction() != null ? log.getAction() : "", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(log.getEntityName() != null ? log.getEntityName() : "", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(log.getEntityId() != null ? log.getEntityId().toString() : "", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(log.getPerformedBy() != null ? log.getPerformedBy() : "", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(log.getTimestamp() != null ? log.getTimestamp().format(formatter) : "", cellFont)));
                table.addCell(new PdfPCell(new Paragraph(log.getDetails() != null ? log.getDetails() : "", cellFont)));
            }
        });
        return out.toByteArray();
    }

    // ==========================================
    // Excel Helpers & Implementation
    // ==========================================
    private byte[] generateExcel(String sheetName, List<String> headers, ExcelDataFiller filler) {
        try (Workbook workbook = new XSSFWorkbook(); ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Sheet sheet = workbook.createSheet(sheetName);

            // Styling Header
            CellStyle headerStyle = workbook.createCellStyle();
            org.apache.poi.ss.usermodel.Font headerFont = workbook.createFont();
            headerFont.setBold(true);
            headerStyle.setFont(headerFont);

            Row headerRow = sheet.createRow(0);
            for (int i = 0; i < headers.size(); i++) {
                Cell cell = headerRow.createCell(i);
                cell.setCellValue(headers.get(i));
                cell.setCellStyle(headerStyle);
            }

            filler.fillExcel(sheet, workbook);

            // Auto-size columns
            for (int i = 0; i < headers.size(); i++) {
                sheet.autoSizeColumn(i);
            }

            workbook.write(out);
            return out.toByteArray();
        } catch (Exception e) {
            logger.error("Error generating Excel report: " + e.getMessage(), e);
            throw new ReportGenerationException("Error generating Excel report: " + e.getMessage());
        }
    }

    interface ExcelDataFiller {
        void fillExcel(Sheet sheet, Workbook workbook);
    }

    @Override
    @Transactional(readOnly = true)
    public byte[] exportProjectsExcel() {
        logger.info("Exporting projects allocation report to Excel");
        List<AllocationResponse> allocations = reportService.getProjectAllocationReport();
        List<String> headers = List.of("ID", "Project Name", "Employee Name", "Allocation %", "Start Date", "End Date", "Status");

        return generateExcel("Project Allocations", headers, (sheet, workbook) -> {
            int rowIdx = 1;
            for (AllocationResponse alloc : allocations) {
                Row row = sheet.createRow(rowIdx++);
                row.createCell(0).setCellValue(alloc.getAllocationId() != null ? alloc.getAllocationId() : 0L);
                row.createCell(1).setCellValue(alloc.getProjectName() != null ? alloc.getProjectName() : "");
                row.createCell(2).setCellValue(alloc.getEmployeeName() != null ? alloc.getEmployeeName() : "");
                row.createCell(3).setCellValue(alloc.getAllocationPercentage() != null ? alloc.getAllocationPercentage() : 0.0);
                row.createCell(4).setCellValue(alloc.getStartDate() != null ? alloc.getStartDate().toString() : "");
                row.createCell(5).setCellValue(alloc.getEndDate() != null ? alloc.getEndDate().toString() : "-");
                row.createCell(6).setCellValue(alloc.getStatus() != null ? alloc.getStatus().toString() : "");
            }
        });
    }

    @Override
    @Transactional(readOnly = true)
    public byte[] exportUtilizationExcel() {
        logger.info("Exporting utilization report to Excel");
        List<UtilizationReportResponse> utils = reportService.getUtilizationReport();
        List<String> headers = List.of("Employee ID", "Employee Name", "Department", "Allocated %", "Billable %", "Bench %");

        return generateExcel("Utilization Report", headers, (sheet, workbook) -> {
            int rowIdx = 1;
            for (UtilizationReportResponse ut : utils) {
                Row row = sheet.createRow(rowIdx++);
                row.createCell(0).setCellValue(ut.getEmployeeId() != null ? ut.getEmployeeId() : 0L);
                row.createCell(1).setCellValue(ut.getEmployeeName() != null ? ut.getEmployeeName() : "");
                row.createCell(2).setCellValue(ut.getDepartment() != null ? ut.getDepartment() : "");
                row.createCell(3).setCellValue(ut.getTotalAllocatedPercentage() != null ? ut.getTotalAllocatedPercentage() : 0.0);
                row.createCell(4).setCellValue(ut.getBillablePercentage() != null ? ut.getBillablePercentage() : 0.0);
                row.createCell(5).setCellValue(ut.getBenchPercentage() != null ? ut.getBenchPercentage() : 100.0);
            }
        });
    }

    @Override
    @Transactional(readOnly = true)
    public byte[] exportSkillsExcel() {
        logger.info("Exporting skills report to Excel");
        List<SkillReportResponse> skills = reportService.getSkillReport();
        List<String> headers = List.of("Skill ID", "Skill Name", "Category", "Count of Employees");

        return generateExcel("Skills Distribution", headers, (sheet, workbook) -> {
            int rowIdx = 1;
            for (SkillReportResponse sk : skills) {
                Row row = sheet.createRow(rowIdx++);
                row.createCell(0).setCellValue(sk.getSkillId() != null ? sk.getSkillId() : 0L);
                row.createCell(1).setCellValue(sk.getSkillName() != null ? sk.getSkillName() : "");
                row.createCell(2).setCellValue(sk.getCategory() != null ? sk.getCategory() : "");
                row.createCell(3).setCellValue(sk.getCount());
            }
        });
    }

    @Override
    @Transactional(readOnly = true)
    public byte[] exportAuditExcel() {
        logger.info("Exporting audit logs to Excel");
        List<AuditLog> logs = auditLogRepository.findAllByOrderByTimestampDesc();
        List<String> headers = List.of("Log ID", "Action", "Entity", "Entity ID", "Performed By", "Timestamp", "Details");

        return generateExcel("Audit Trail", headers, (sheet, workbook) -> {
            int rowIdx = 1;
            for (AuditLog log : logs) {
                Row row = sheet.createRow(rowIdx++);
                row.createCell(0).setCellValue(log.getLogId() != null ? log.getLogId() : 0L);
                row.createCell(1).setCellValue(log.getAction() != null ? log.getAction() : "");
                row.createCell(2).setCellValue(log.getEntityName() != null ? log.getEntityName() : "");
                row.createCell(3).setCellValue(log.getEntityId() != null ? log.getEntityId() : 0L);
                row.createCell(4).setCellValue(log.getPerformedBy() != null ? log.getPerformedBy() : "");
                row.createCell(5).setCellValue(log.getTimestamp() != null ? log.getTimestamp().format(formatter) : "");
                row.createCell(6).setCellValue(log.getDetails() != null ? log.getDetails() : "");
            }
        });
    }

    // ==========================================
    // Word (XWPF) Helpers & Implementation
    // ==========================================
    @Override
    @Transactional(readOnly = true)
    public byte[] exportProjectsWord() {
        logger.info("Exporting projects allocation report to Word (DOCX)");
        List<AllocationResponse> allocations = reportService.getProjectAllocationReport();

        try (XWPFDocument document = new XWPFDocument(); ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            XWPFParagraph titlePara = document.createParagraph();
            XWPFRun titleRun = titlePara.createRun();
            titleRun.setText("Project Allocations Report");
            titleRun.setBold(true);
            titleRun.setFontSize(16);
            titlePara.setSpacingAfter(20);

            XWPFParagraph metaPara = document.createParagraph();
            XWPFRun metaRun = metaPara.createRun();
            metaRun.setText("Generated Date: " + LocalDateTime.now().format(formatter) + " | Generated By: ERASM Admin");
            metaRun.setFontSize(10);
            metaPara.setSpacingAfter(15);

            XWPFTable table = document.createTable();
            
            // Header Row
            XWPFTableRow headerRow = table.getRow(0);
            String[] headers = {"ID", "Project Name", "Employee Name", "Allocation %", "Start Date", "End Date", "Status"};
            headerRow.getCell(0).setText(headers[0]);
            for (int i = 1; i < headers.length; i++) {
                headerRow.addNewTableCell().setText(headers[i]);
            }

            for (AllocationResponse alloc : allocations) {
                XWPFTableRow row = table.createRow();
                row.getCell(0).setText(alloc.getAllocationId() != null ? alloc.getAllocationId().toString() : "");
                row.getCell(1).setText(alloc.getProjectName() != null ? alloc.getProjectName() : "");
                row.getCell(2).setText(alloc.getEmployeeName() != null ? alloc.getEmployeeName() : "");
                row.getCell(3).setText(alloc.getAllocationPercentage() != null ? alloc.getAllocationPercentage().toString() + "%" : "0%");
                row.getCell(4).setText(alloc.getStartDate() != null ? alloc.getStartDate().toString() : "");
                row.getCell(5).setText(alloc.getEndDate() != null ? alloc.getEndDate().toString() : "-");
                row.getCell(6).setText(alloc.getStatus() != null ? alloc.getStatus().toString() : "");
            }

            document.write(out);
            return out.toByteArray();
        } catch (Exception e) {
            logger.error("Error generating Word document: " + e.getMessage(), e);
            throw new ReportGenerationException("Error generating Word report: " + e.getMessage());
        }
    }
}
